from .views import *
from .partner_update import PartnerUpdate
from .partner_state import PartnerState
from .partner_orders import PartnerOrders
from .product_info import ProductInfoView
from .basket import BasketView
from .contact import ContactView
from .order import OrderView
from .register_account import RegisterAccount
from .confirm_account import ConfirmAccount
from .account_details import AccountDetails
from .shop import ShopView
from .category import CategoryView
from .login_account import LoginAccount
